spring:
  datasource:
#    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    url: jdbc:h2:tcp://localhost/~/mylittlestore
    username: cha3088
    password: ${DB_PASSWORD}
    driver-class-name: org.h2.Driver
    test: classpath*:sql/test.sql
  jpa:
    hibernate:
      ddl-auto: create
    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true
      logging.level:
        org.hibernate.SQL: debug
#        org.hibernate.type: trace
#        org.hibernate.type:
#          descriptor:
#            sql: trace
    open-in-view: false
# p6spy
logging:
  level:
    p6spy: info
decorator:
  datasource:
    p6spy:
      enable-logging: true
# p6spy